language: python

matrix:
  include:
    - python: 2.6
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: "nightly"
      env: PRE=--pre
  allow_failures:
    - python : "nightly"

install:
  - python setup.py install
  - pip install coveralls six

script:
  - python run_tests.py

after_success:
  coveralls
