language: python

matrix:
  include:
    - python: 2.6
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: "nightly"
      env: PRE=--pre
  allow_failures:
    - python : "nightly"

install:
  - pip install nose coveralls matplotlib flake8
  - python setup.py install

script:
  - python run_tests.py

  - flake8 --exit-zero trendvis

after_success:
  coveralls
